"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

#: Base directory for the demo project.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-f^bd0hzl91f=xkvt(=+)lsasd&ljgqp(egaf0@(oevyswc-7iu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#: Allowed hostnames for the Django server.
ALLOWED_HOSTS: list[str] = []


# Application definition

#: Installed Django applications.
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "demo.core",
    "book_manager",
    "rest_framework",
]

#: Middleware stack for incoming requests.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

#: Root URL configuration module.
ROOT_URLCONF = "demo.urls"

#: Template backend configuration.
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

#: WSGI application entry point.
WSGI_APPLICATION = "demo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#: Database configuration for the demo project.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

#: Password validation backends.
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

#: Default language code.
LANGUAGE_CODE = "en-us"

#: Default application time zone.
TIME_ZONE = "UTC"

#: Enable Django internationalization support.
USE_I18N = True

#: Store datetimes as timezone-aware values.
USE_TZ = True

#: Cognito machine-to-machine authentication settings for the demo API.
COGNITO_M2M = {
    "REGION": os.environ.get("COGNITO_M2M_REGION"),
    "USER_POOL_ID": os.environ.get("COGNITO_M2M_USER_POOL_ID"),
    "AUDIENCE": os.environ.get("COGNITO_M2M_AUDIENCE") or None,
}
print(COGNITO_M2M)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

#: Base URL for static assets.
STATIC_URL = "static/"
